FROM python:3.12-slim

RUN pip install --no-cache-dir mlflow[extras]==2.15.0 boto3 pymysql

EXPOSE 5000

ENV MLFLOW_HOST=0.0.0.0
ENV MLFLOW_PORT=5000

CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000"]
